[2017-05-21 00:43:22 +0000] [3290] [INFO] Starting gunicorn 19.7.1
[2017-05-21 00:43:22 +0000] [3290] [INFO] Listening at: http://0.0.0.0:90 (3290)
[2017-05-21 00:43:22 +0000] [3290] [INFO] Using worker: sync
[2017-05-21 00:43:22 +0000] [3295] [INFO] Booting worker with pid: 3295
[2017-05-21 00:43:22 +0000] [3296] [INFO] Booting worker with pid: 3296
[2017-05-21 00:43:22 +0000] [3301] [INFO] Booting worker with pid: 3301
[2017-05-21 00:43:22 +0000] [3302] [INFO] Booting worker with pid: 3302
[2017-05-21 00:49:28,494] ERROR in app: Exception on /v1.0/location [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 87, in loaction
    currentUser.latitude=latitude
AttributeError: 'NoneType' object has no attribute 'latitude'
[2017-05-21 00:49:33,331] ERROR in app: Exception on /v1.0/location [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 87, in loaction
    currentUser.latitude=latitude
AttributeError: 'NoneType' object has no attribute 'latitude'
[2017-05-21 01:38:30 +0000] [3290] [INFO] Handling signal: term
[2017-05-21 01:38:30 +0000] [3296] [INFO] Worker exiting (pid: 3296)
[2017-05-21 01:38:30 +0000] [3295] [INFO] Worker exiting (pid: 3295)
[2017-05-21 01:38:30 +0000] [3301] [INFO] Worker exiting (pid: 3301)
[2017-05-21 01:38:30 +0000] [3302] [INFO] Worker exiting (pid: 3302)
[2017-05-21 01:38:30 +0000] [3290] [INFO] Shutting down: Master
[2017-05-21 08:18:45 +0000] [1313] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:18:45 +0000] [1313] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:18:45 +0000] [1313] [ERROR] Retrying in 1 second.
[2017-05-21 08:18:46 +0000] [1313] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:18:46 +0000] [1313] [ERROR] Retrying in 1 second.
[2017-05-21 08:18:47 +0000] [1313] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:18:47 +0000] [1313] [ERROR] Retrying in 1 second.
[2017-05-21 08:18:48 +0000] [1313] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:18:48 +0000] [1313] [ERROR] Retrying in 1 second.
[2017-05-21 08:18:49 +0000] [1313] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:18:49 +0000] [1313] [ERROR] Retrying in 1 second.
[2017-05-21 08:18:50 +0000] [1313] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:21:44 +0000] [1689] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:21:44 +0000] [1689] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:44 +0000] [1689] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:45 +0000] [1689] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:45 +0000] [1689] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:46 +0000] [1689] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:46 +0000] [1689] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:47 +0000] [1689] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:47 +0000] [1689] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:48 +0000] [1689] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:48 +0000] [1689] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:49 +0000] [1689] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:21:50 +0000] [2012] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:21:50 +0000] [2012] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:50 +0000] [2012] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:51 +0000] [2012] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:51 +0000] [2012] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:52 +0000] [2012] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:52 +0000] [2012] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:53 +0000] [2012] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:53 +0000] [2012] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:54 +0000] [2012] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:54 +0000] [2012] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:55 +0000] [2012] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:21:56 +0000] [2117] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:21:56 +0000] [2117] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:56 +0000] [2117] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:57 +0000] [2117] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:57 +0000] [2117] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:58 +0000] [2117] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:58 +0000] [2117] [ERROR] Retrying in 1 second.
[2017-05-21 08:21:59 +0000] [2117] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:21:59 +0000] [2117] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:00 +0000] [2117] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:00 +0000] [2117] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:01 +0000] [2117] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:03 +0000] [2124] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:03 +0000] [2124] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:03 +0000] [2124] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:04 +0000] [2124] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:04 +0000] [2124] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:05 +0000] [2124] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:05 +0000] [2124] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:06 +0000] [2124] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:06 +0000] [2124] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:07 +0000] [2124] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:07 +0000] [2124] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:08 +0000] [2124] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:09 +0000] [2167] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:09 +0000] [2167] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:09 +0000] [2167] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:10 +0000] [2167] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:10 +0000] [2167] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:11 +0000] [2167] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:11 +0000] [2167] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:12 +0000] [2167] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:12 +0000] [2167] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:13 +0000] [2167] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:13 +0000] [2167] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:14 +0000] [2167] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:16 +0000] [2175] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:16 +0000] [2175] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:16 +0000] [2175] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:17 +0000] [2175] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:17 +0000] [2175] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:18 +0000] [2175] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:18 +0000] [2175] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:19 +0000] [2175] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:19 +0000] [2175] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:20 +0000] [2175] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:20 +0000] [2175] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:21 +0000] [2175] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:22 +0000] [2183] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:22 +0000] [2183] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:22 +0000] [2183] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:23 +0000] [2183] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:23 +0000] [2183] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:24 +0000] [2183] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:24 +0000] [2183] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:25 +0000] [2183] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:25 +0000] [2183] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:26 +0000] [2183] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:26 +0000] [2183] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:27 +0000] [2183] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:28 +0000] [2203] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:28 +0000] [2203] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:28 +0000] [2203] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:29 +0000] [2203] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:29 +0000] [2203] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:30 +0000] [2203] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:30 +0000] [2203] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:31 +0000] [2203] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:31 +0000] [2203] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:32 +0000] [2203] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:32 +0000] [2203] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:33 +0000] [2203] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:35 +0000] [2288] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:35 +0000] [2288] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:35 +0000] [2288] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:36 +0000] [2288] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:36 +0000] [2288] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:37 +0000] [2288] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:37 +0000] [2288] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:38 +0000] [2288] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:38 +0000] [2288] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:39 +0000] [2288] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:39 +0000] [2288] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:40 +0000] [2288] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:41 +0000] [2322] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:41 +0000] [2322] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:41 +0000] [2322] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:42 +0000] [2322] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:42 +0000] [2322] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:43 +0000] [2322] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:43 +0000] [2322] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:44 +0000] [2322] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:44 +0000] [2322] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:45 +0000] [2322] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:45 +0000] [2322] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:46 +0000] [2322] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:47 +0000] [2337] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:47 +0000] [2337] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:47 +0000] [2337] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:48 +0000] [2337] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:48 +0000] [2337] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:49 +0000] [2337] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:49 +0000] [2337] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:50 +0000] [2337] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:50 +0000] [2337] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:51 +0000] [2337] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:51 +0000] [2337] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:52 +0000] [2337] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:22:54 +0000] [2365] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:22:54 +0000] [2365] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:54 +0000] [2365] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:55 +0000] [2365] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:55 +0000] [2365] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:56 +0000] [2365] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:56 +0000] [2365] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:57 +0000] [2365] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:57 +0000] [2365] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:58 +0000] [2365] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:22:58 +0000] [2365] [ERROR] Retrying in 1 second.
[2017-05-21 08:22:59 +0000] [2365] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:00 +0000] [2370] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:00 +0000] [2370] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:00 +0000] [2370] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:01 +0000] [2370] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:01 +0000] [2370] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:02 +0000] [2370] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:02 +0000] [2370] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:03 +0000] [2370] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:03 +0000] [2370] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:04 +0000] [2370] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:04 +0000] [2370] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:05 +0000] [2370] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:06 +0000] [2378] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:06 +0000] [2378] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:06 +0000] [2378] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:07 +0000] [2378] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:07 +0000] [2378] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:08 +0000] [2378] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:08 +0000] [2378] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:09 +0000] [2378] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:09 +0000] [2378] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:10 +0000] [2378] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:10 +0000] [2378] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:11 +0000] [2378] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:13 +0000] [2383] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:13 +0000] [2383] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:13 +0000] [2383] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:14 +0000] [2383] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:14 +0000] [2383] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:15 +0000] [2383] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:15 +0000] [2383] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:16 +0000] [2383] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:16 +0000] [2383] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:17 +0000] [2383] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:17 +0000] [2383] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:18 +0000] [2383] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:19 +0000] [2389] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:19 +0000] [2389] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:19 +0000] [2389] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:20 +0000] [2389] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:20 +0000] [2389] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:21 +0000] [2389] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:21 +0000] [2389] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:22 +0000] [2389] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:22 +0000] [2389] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:23 +0000] [2389] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:23 +0000] [2389] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:24 +0000] [2389] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:26 +0000] [2395] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:26 +0000] [2395] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:26 +0000] [2395] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:27 +0000] [2395] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:27 +0000] [2395] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:28 +0000] [2395] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:28 +0000] [2395] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:29 +0000] [2395] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:29 +0000] [2395] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:30 +0000] [2395] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:30 +0000] [2395] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:31 +0000] [2395] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:32 +0000] [2400] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:32 +0000] [2400] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:32 +0000] [2400] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:33 +0000] [2400] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:33 +0000] [2400] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:34 +0000] [2400] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:34 +0000] [2400] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:35 +0000] [2400] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:35 +0000] [2400] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:36 +0000] [2400] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:36 +0000] [2400] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:37 +0000] [2400] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:37 +0000] [2405] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:37 +0000] [2405] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:37 +0000] [2405] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:38 +0000] [2405] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:38 +0000] [2405] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:39 +0000] [2405] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:39 +0000] [2405] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:40 +0000] [2405] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:40 +0000] [2405] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:41 +0000] [2405] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:41 +0000] [2405] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:42 +0000] [2405] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:44 +0000] [2410] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:44 +0000] [2410] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:44 +0000] [2410] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:45 +0000] [2410] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:45 +0000] [2410] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:46 +0000] [2410] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:46 +0000] [2410] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:47 +0000] [2410] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:47 +0000] [2410] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:48 +0000] [2410] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:48 +0000] [2410] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:49 +0000] [2410] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:50 +0000] [2425] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:50 +0000] [2425] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:50 +0000] [2425] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:51 +0000] [2425] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:51 +0000] [2425] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:52 +0000] [2425] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:52 +0000] [2425] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:53 +0000] [2425] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:53 +0000] [2425] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:54 +0000] [2425] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:54 +0000] [2425] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:55 +0000] [2425] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:23:56 +0000] [2430] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:23:56 +0000] [2430] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:56 +0000] [2430] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:57 +0000] [2430] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:57 +0000] [2430] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:58 +0000] [2430] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:58 +0000] [2430] [ERROR] Retrying in 1 second.
[2017-05-21 08:23:59 +0000] [2430] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:23:59 +0000] [2430] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:00 +0000] [2430] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:00 +0000] [2430] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:01 +0000] [2430] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:03 +0000] [2435] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:03 +0000] [2435] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:03 +0000] [2435] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:04 +0000] [2435] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:04 +0000] [2435] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:05 +0000] [2435] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:05 +0000] [2435] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:06 +0000] [2435] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:06 +0000] [2435] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:07 +0000] [2435] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:07 +0000] [2435] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:08 +0000] [2435] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:09 +0000] [2440] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:09 +0000] [2440] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:09 +0000] [2440] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:10 +0000] [2440] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:10 +0000] [2440] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:11 +0000] [2440] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:11 +0000] [2440] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:12 +0000] [2440] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:12 +0000] [2440] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:13 +0000] [2440] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:13 +0000] [2440] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:14 +0000] [2440] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:15 +0000] [2445] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:15 +0000] [2445] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:15 +0000] [2445] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:16 +0000] [2445] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:16 +0000] [2445] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:17 +0000] [2445] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:17 +0000] [2445] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:18 +0000] [2445] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:18 +0000] [2445] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:19 +0000] [2445] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:19 +0000] [2445] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:20 +0000] [2445] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:22 +0000] [2450] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:22 +0000] [2450] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:22 +0000] [2450] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:23 +0000] [2450] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:23 +0000] [2450] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:24 +0000] [2450] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:24 +0000] [2450] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:25 +0000] [2450] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:25 +0000] [2450] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:26 +0000] [2450] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:26 +0000] [2450] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:27 +0000] [2450] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:28 +0000] [2456] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:28 +0000] [2456] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:28 +0000] [2456] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:29 +0000] [2456] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:29 +0000] [2456] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:30 +0000] [2456] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:30 +0000] [2456] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:31 +0000] [2456] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:31 +0000] [2456] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:32 +0000] [2456] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:32 +0000] [2456] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:33 +0000] [2456] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:35 +0000] [2461] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:35 +0000] [2461] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:35 +0000] [2461] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:36 +0000] [2461] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:36 +0000] [2461] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:37 +0000] [2461] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:37 +0000] [2461] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:38 +0000] [2461] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:38 +0000] [2461] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:39 +0000] [2461] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:39 +0000] [2461] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:40 +0000] [2461] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:41 +0000] [2468] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:41 +0000] [2468] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:41 +0000] [2468] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:42 +0000] [2468] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:42 +0000] [2468] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:43 +0000] [2468] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:43 +0000] [2468] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:44 +0000] [2468] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:44 +0000] [2468] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:45 +0000] [2468] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:45 +0000] [2468] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:46 +0000] [2468] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:47 +0000] [2475] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:47 +0000] [2475] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:47 +0000] [2475] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:48 +0000] [2475] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:48 +0000] [2475] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:49 +0000] [2475] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:49 +0000] [2475] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:50 +0000] [2475] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:50 +0000] [2475] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:51 +0000] [2475] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:51 +0000] [2475] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:52 +0000] [2475] [ERROR] Can't connect to ('0.0.0.0', 90)
[2017-05-21 08:24:54 +0000] [2480] [INFO] Starting gunicorn 19.7.1
[2017-05-21 08:24:54 +0000] [2480] [ERROR] Connection in use: ('0.0.0.0', 90)
[2017-05-21 08:24:54 +0000] [2480] [ERROR] Retrying in 1 second.
[2017-05-21 08:24:55 +0000] [2480] [INFO] Listening at: http://0.0.0.0:90 (2480)
[2017-05-21 08:24:55 +0000] [2480] [INFO] Using worker: sync
[2017-05-21 08:24:55 +0000] [2492] [INFO] Booting worker with pid: 2492
[2017-05-21 08:24:55 +0000] [2493] [INFO] Booting worker with pid: 2493
[2017-05-21 08:24:55 +0000] [2494] [INFO] Booting worker with pid: 2494
[2017-05-21 08:24:55 +0000] [2495] [INFO] Booting worker with pid: 2495
[2017-05-21 13:15:00,834] ERROR in app: Exception on /v1.0/location [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 87, in loaction
    if latitude==None or longitude==None:
AttributeError: 'NoneType' object has no attribute 'latitude'
[2017-05-21 13:16:14,737] ERROR in app: Exception on /v1.0/location [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 87, in loaction
    if latitude==None or longitude==None:
AttributeError: 'NoneType' object has no attribute 'latitude'
[2017-05-21 18:55:24 +0000] [2480] [CRITICAL] WORKER TIMEOUT (pid:2495)
[2017-05-21 18:55:24 +0000] [2495] [INFO] Worker exiting (pid: 2495)
[2017-05-21 18:55:24 +0000] [12595] [INFO] Booting worker with pid: 12595
[2017-05-21 18:55:54 +0000] [2480] [CRITICAL] WORKER TIMEOUT (pid:2492)
[2017-05-21 18:55:54 +0000] [2492] [INFO] Worker exiting (pid: 2492)
[2017-05-21 18:55:54 +0000] [12645] [INFO] Booting worker with pid: 12645
[2017-05-21 19:46:51,485] ERROR in app: Exception on /v1.0/abortgroup [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 113, in abort
    groupId=request.json['groupId']
KeyError: 'groupId'
[2017-05-21 19:47:07,433] ERROR in app: Exception on /v1.0/abortgroup [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 113, in abort
    groupId=request.json['groupId']
KeyError: 'groupId'
[2017-05-21 19:47:17,835] ERROR in app: Exception on /v1.0/abortgroup [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 113, in abort
    groupId=request.json['groupId']
KeyError: 'groupId'
[2017-05-21 20:39:35,009] ERROR in app: Exception on /v1.0/abortgroup [POST]
Traceback (most recent call last):
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yz/Desktop/WEB-API/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yz/Desktop/WEB-API/app/views.py", line 113, in abort
    groupId=request.json['groupId']
KeyError: 'groupId'
